# Generated by Django 4.1 on 2022-08-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=5, verbose_name='Temperature in C')),
                ('wind', models.CharField(max_length=50, verbose_name='Wind')),
                ('pressure', models.CharField(max_length=50, verbose_name='Pressure')),
                ('clouds', models.CharField(max_length=50, verbose_name='Clouds')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('icon', models.CharField(max_length=200, verbose_name='Icon')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='city.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weather',
                'ordering': ['-created'],
            },
        ),
    ]
