# Generated by Django 4.1 on 2022-08-23 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weather_forecast', to='city.city', verbose_name='City_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weather_forecast', to=settings.AUTH_USER_MODEL, verbose_name='User_id')),
            ],
            options={
                'verbose_name': 'weather forecast',
                'verbose_name_plural': 'weather forecast',
                'ordering': ['-created'],
            },
        ),
    ]
